export const VERIFY_TIMEOUT_MS = 4000;
export const MAX_IMAGE_TURNS_IN_CONTEXT = 6;
export const MAX_INSPECT_RESULT_CHARS = 12000;
export const API_SCREENSHOT_JPEG_QUALITY = 70;
export const GENERATION_JOB_LOCK_DURATION_MS = 2 * 60 * 60 * 1000;
export const GENERATION_STALE_GRACE_MS = 5 * 60 * 1000;
export const ACCESS_BARRIER_VERIFY_PREFIX = 'ACCESS_BARRIER:';
