import { BlockRule } from './block-handling.interface';

export const DEFAULT_WAIT_TIMEOUT_MS = 20_000;
export const DEFAULT_MIN_READY_BODY_LENGTH = 80;
export const PENDING_BODY_LENGTH_THRESHOLD = 40;

export const DEFAULT_BLOCK_RULES: BlockRule[] = [
  {
    id: 'cloudfront-request-not-satisfied-title',
    signal: 'blocked',
    source: 'title',
    pattern: 'ERROR: The request could not be satisfied',
  },
  {
    id: 'cloudfront-request-blocked-text',
    signal: 'blocked',
    source: 'text',
    pattern: 'Request blocked',
  },
  {
    id: 'cloudfront-403-text',
    signal: 'blocked',
    source: 'text',
    pattern: '403 ERROR',
  },
  {
    id: 'cloudfront-generated-by',
    signal: 'blocked',
    source: 'text',
    pattern: 'Generated by cloudfront \\(CloudFront\\)',
    regex: true,
  },
  {
    id: 'cloudfront-request-blocked-html',
    signal: 'blocked',
    source: 'html',
    pattern: 'Request blocked',
  },
  {
    id: 'cloudfront-403-html',
    signal: 'blocked',
    source: 'html',
    pattern: '403 ERROR',
  },
  {
    id: 'cloudfront-generated-by-html',
    signal: 'blocked',
    source: 'html',
    pattern: 'Generated by cloudfront',
    regex: true,
  },
  {
    id: 'access-denied-title',
    signal: 'blocked',
    source: 'title',
    pattern: 'Access Denied',
    regex: true,
  },
  {
    id: 'aws-waf-challenge-script',
    signal: 'challenge',
    source: 'script_content',
    pattern: 'aws.?waf|awswaf|challenge\\.js',
    regex: true,
  },
  {
    id: 'imperva-resource-script',
    signal: 'challenge',
    source: 'script_content',
    pattern: '_Incapsula_Resource',
  },
  {
    id: 'imperva-pardon-html',
    signal: 'challenge',
    source: 'html',
    pattern: 'Pardon Our Interruption',
  },
  {
    id: 'imperva-pardon-title',
    signal: 'challenge',
    source: 'title',
    pattern: 'Pardon Our Interruption',
  },
  {
    id: 'imperva-pardon-text',
    signal: 'challenge',
    source: 'text',
    pattern: 'Pardon Our Interruption',
  },
  {
    id: 'imperva-incident-id-text',
    signal: 'challenge',
    source: 'text',
    pattern: 'Your support ID is',
  },
];
